"use client";
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {z} from 'zod';
import {CandleSchema,IndicatorSchema,Symbols,Intervals} from '../../lib/market';
import {createChartAdapter,type ChartAdapter} from '../../lib/chart-adapter';
const Decision=z.object({event_id:z.string().regex(/^[0-9a-f]{64}$/),schema_version:z.literal(1),type:z.literal('TARGET_DECISION'),rule:z.literal('target-on-close-v1'),strategy:z.enum(['ema_long_flat_v1','sma_long_flat_v1']),strategy_version:z.literal(1),parameters:z.record(z.string(),z.unknown()),bar_open_time:z.iso.datetime({offset:true}),available_at:z.iso.datetime({offset:true}),target:z.enum(['LONG','FLAT']),execution:z.literal('NOT_IMPLEMENTED')});
const State=z.object({session_id:z.uuid(),revision:z.number().int().nonnegative(),cursor:z.number().int().nonnegative(),total:z.number().int().min(2).max(1000),status:z.enum(['READY','ENDED']),clock:z.iso.datetime({offset:true}),trading_enabled:z.literal(false),manifest:z.object({version:z.enum(['closed-bar-replay-v1','closed-bar-replay-v2']),strategy:z.enum(['ema_long_flat_v1','sma_long_flat_v1']).nullable().optional(),strategy_version:z.number().int().nullable().optional(),parameters:z.record(z.string(),z.unknown()).nullable().optional(),decision_rule:z.literal('target-on-close-v1').optional(),symbol:z.enum(Symbols),timeframe:z.enum(Intervals),period:z.number().int(),snapshot_sha256:z.string(),as_of:z.iso.datetime({offset:true}),start:z.iso.datetime({offset:true}),end:z.iso.datetime({offset:true})}),candles:z.array(CandleSchema),indicators:IndicatorSchema.shape.rows,decisions:z.array(Decision).default([])}).superRefine((state,context)=>{
 if(state.cursor>state.total||state.candles.length!==state.cursor||state.indicators.length!==state.cursor)context.addIssue({code:'custom',message:'Invalid replay prefix'});
 const clock=Date.parse(state.clock);
 if(state.candles.some(bar=>!bar.is_closed||Date.parse(bar.close_time)>clock)||state.indicators.some(row=>Date.parse(row.available_at)>clock))context.addIssue({code:'custom',message:'Future replay data rejected'});
 const reached=new Map(state.candles.map(bar=>[Date.parse(bar.open_time),Date.parse(bar.close_time)]));
 if(state.decisions.some(event=>Date.parse(event.available_at)>clock||reached.get(Date.parse(event.bar_open_time))!==Date.parse(event.available_at)))context.addIssue({code:'custom',message:'Future decision rejected'});
});
type View=z.infer<typeof State>;
const KEY='fc666.replay.session.v1',SPEED_KEY='fc666.replay.speed.v1';
export default function Replay(){
 const [strategy,setStrategy]=useState('none'),[fast,setFast]=useState('10'),[slow,setSlow]=useState('20');
 const [symbol,setSymbol]=useState('BTCUSDT'),[timeframe,setTimeframe]=useState('1h'),[limit,setLimit]=useState('120'),[period,setPeriod]=useState('20'),[cutoff,setCutoff]=useState('');
 const [view,setView]=useState<View|null>(null),[busy,setBusy]=useState(false),[playing,setPlaying]=useState(false),[speed,setSpeed]=useState(1),[indicators,setIndicators]=useState(false),[follow,setFollow]=useState(true),[error,setError]=useState('');
 const audit=useRef<Record<string,unknown>|null>(null);
 const current=useRef<View|null>(null),locked=useRef(false),element=useRef<HTMLDivElement>(null),chart=useRef<ChartAdapter|null>(null);
 function adopt(next:View){current.current=next;setView(next);localStorage.setItem(KEY,next.session_id);if(next.status==='ENDED')setPlaying(false);}
 async function read(id:string,signal?:AbortSignal){const response=await fetch(`/api/replay/sessions/${id}`,{cache:'no-store',signal:signal??AbortSignal.timeout(15000)});if(response.status===404){localStorage.removeItem(KEY);current.current=null;setView(null);throw new Error('回放会话不存在');}if(!response.ok)throw new Error('回放状态不可用');const data=await response.json();const next=State.parse(data);audit.current=data;return next;}
 useEffect(()=>{if(element.current){chart.current=createChartAdapter(element.current);return()=>{chart.current?.dispose();chart.current=null;};}},[]);
 useEffect(()=>{chart.current?.setHistory(view?.candles??[]);chart.current?.setIndicators(view?.indicators??[],indicators);if(follow&&view?.cursor)chart.current?.fit();},[view,indicators,follow]);
 useEffect(()=>{const saved=localStorage.getItem(KEY),savedSpeed=Number(localStorage.getItem(SPEED_KEY));if([.5,1,2,4].includes(savedSpeed))setSpeed(savedSpeed);if(!saved||!z.uuid().safeParse(saved).success)return;const abort=new AbortController();locked.current=true;setBusy(true);void read(saved,abort.signal).then(next=>{if(!abort.signal.aborted){adopt(next);setSymbol(next.manifest.symbol);setTimeframe(next.manifest.timeframe);setLimit(String(next.total));setPeriod(String(next.manifest.period));setCutoff(next.manifest.as_of);setStrategy(next.manifest.strategy??'none');if(next.manifest.parameters){setFast(String(next.manifest.parameters.fast??10));setSlow(String(next.manifest.parameters.slow??20));}}}).catch(e=>{if(!abort.signal.aborted)setError(e instanceof Error?e.message:'恢复失败');}).finally(()=>{if(!abort.signal.aborted){locked.current=false;setBusy(false);}});return()=>abort.abort();},[]);
 async function create(event:FormEvent){event.preventDefault();if(locked.current)return;locked.current=true;setBusy(true);setPlaying(false);setError('');current.current=null;audit.current=null;setView(null);localStorage.removeItem(KEY);
  try{const response=await fetch('/api/replay/sessions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({symbol,timeframe,limit:Number(limit),period:Number(period),as_of:cutoff||null,strategy:strategy==='none'?null:strategy,parameters:strategy==='none'?null:strategy==='ema_long_flat_v1'?{period:Number(period)}:{fast:Number(fast),slow:Number(slow)}}),signal:AbortSignal.timeout(15000)});const data=await response.json();if(!response.ok)throw new Error(typeof data.detail==='string'?data.detail:'回放参数或历史数据不可用');const next=State.parse(data);audit.current=data;adopt(next);}
  catch(e){setError(e instanceof Error?e.message:'创建失败');}finally{locked.current=false;setBusy(false);}
 }
 async function command(action:'step'|'reset'){
  const before=current.current;if(!before||locked.current)return;locked.current=true;setBusy(true);setError('');
  try{const response=await fetch(`/api/replay/sessions/${before.session_id}/command`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({expected_revision:before.revision,action,count:1}),signal:AbortSignal.timeout(15000)});if(!response.ok)throw new Error(response.status===409?'回放版本冲突，已暂停并同步进度':'推进未确认，已暂停并尝试同步进度');const data=await response.json();const next=State.parse(data);if(next.session_id!==before.session_id||next.manifest.snapshot_sha256!==before.manifest.snapshot_sha256)throw new Error('回放快照不一致');audit.current=data;adopt(next);}
  catch(e){setPlaying(false);setError(e instanceof Error?e.message:'回放连接失败');try{adopt(await read(before.session_id));}catch{/* Preserve last acknowledged prefix; never retry a mutation automatically. */}}
  finally{locked.current=false;setBusy(false);}
 }
 useEffect(()=>{if(!playing||!view)return;let active=true;let timer:ReturnType<typeof setTimeout>;
  async function tick(){if(!active)return;if(locked.current){timer=setTimeout(tick,50);return;}await command('step');if(active&&current.current?.status!=='ENDED')timer=setTimeout(tick,1000/speed);}
  timer=setTimeout(tick,1000/speed);return()=>{active=false;clearTimeout(timer);};
 },[playing,speed,view?.session_id]);
 const labels={UNAVAILABLE:'预热中',RANGE:'震荡',TREND_UP:'上行趋势',TREND_DOWN:'下行趋势'};
 const last=view?.candles.at(-1),latest=view?.indicators.at(-1);
 return <main className="research-page replay-page"><header><strong>FC666 · Replay</strong><a href="/">行情终端</a><a href="/research">研究</a><span className="badge">历史闭合柱 · 实盘关闭</span></header><h1>历史市场回放</h1><p>使用固定历史快照按闭合柱推进。页面只获取已到达的价格与指标，不订阅实时行情。当前不含逐笔成交、历史订单簿、柱内路径或模拟下单。</p>
 <form className="research-form" onSubmit={create}><label>回放策略<select aria-label="回放策略" value={strategy} onChange={e=>setStrategy(e.target.value)}><option value="none">只回放行情</option><option value="ema_long_flat_v1">EMA Long / Flat v1</option><option value="sma_long_flat_v1">SMA Long / Flat v1</option></select></label>{strategy==='sma_long_flat_v1'?<><label>回放 SMA 快周期<input required type="number" min="2" max="499" value={fast} onChange={e=>setFast(e.target.value)}/></label><label>回放 SMA 慢周期<input required type="number" min={Number(fast)+1} max="500" value={slow} onChange={e=>setSlow(e.target.value)}/></label></>:null}<label>回放交易对<select aria-label="回放交易对" value={symbol} onChange={e=>setSymbol(e.target.value)}>{Symbols.map(value=><option key={value}>{value}</option>)}</select></label><label>回放周期<select aria-label="回放周期" value={timeframe} onChange={e=>setTimeframe(e.target.value)}>{Intervals.map(value=><option key={value}>{value}</option>)}</select></label><label>回放柱数<input required type="number" min="2" max="1000" value={limit} onChange={e=>setLimit(e.target.value)}/></label><label>回放均线周期<input required type="number" min="2" max="500" value={period} onChange={e=>setPeriod(e.target.value)}/></label><label>回放截止时间（含时区，可空）<input value={cutoff} onChange={e=>setCutoff(e.target.value)} placeholder="2026-10-06T00:00:00Z"/></label><button disabled={busy||playing} type="submit">创建固定回放</button></form>
 {error?<p role="alert">{error}</p>:null}
 {view?<section data-testid="replay-state" data-cursor={view.cursor} data-revision={view.revision} data-playing={playing} data-status={view.status}><h2>{view.manifest.symbol} · {view.manifest.timeframe} · {view.cursor}/{view.total} 根</h2><p>回放时钟 UTC：<time data-testid="replay-clock">{view.clock}</time> · {view.status==='ENDED'?'已结束':playing?'播放中':busy?'暂停 · 正在确认当前步':'已暂停'}</p><progress aria-label="回放进度" max={view.total} value={view.cursor}/><div className="replay-controls"><button disabled={busy||playing||view.status==='ENDED'} onClick={()=>void command('step')}>推进一根</button><button disabled={!playing&&(busy||view.status==='ENDED')} onClick={()=>setPlaying(value=>!value)}>{playing?'暂停回放':'播放回放'}</button><button disabled={busy} onClick={()=>{setPlaying(false);void command('reset');}}>从头重置</button><label>回放速度<select aria-label="回放速度" value={speed} onChange={e=>{const value=Number(e.target.value);setSpeed(value);localStorage.setItem(SPEED_KEY,String(value));}}>{[.5,1,2,4].map(value=><option key={value} value={value}>{value} 根/秒（目标）</option>)}</select></label><button aria-pressed={follow} onClick={()=>setFollow(value=>!value)}>跟随回放</button><button aria-pressed={indicators} onClick={()=>setIndicators(value=>!value)}>回放指标</button></div><p>最新已到达收盘：<span data-testid="replay-close">{last?.close??'尚未推进'}</span> · EMA{view.manifest.period}：{latest?.values.ema??'预热中'} · 当前分类：{latest?labels[latest.regime.label]:'预热中'}</p><details><summary>回放快照信息</summary><p>固定截止 {view.manifest.as_of} · 范围 {view.manifest.start} 至 {view.manifest.end}</p><p style={{overflowWrap:'anywhere'}}>SHA256: {view.manifest.snapshot_sha256}</p><p>刷新默认暂停，恢复最后已确认的进度。版本冲突或网络错误会暂停并读取服务器进度，不自动重发推进请求。暂停时已经发出的当前步仍可能完成。</p></details></section>:<p>创建回放后从零根开始；每次推进只开放下一根完整闭合柱。</p>}
 {view?<section data-testid="replay-decisions" data-count={view.decisions.length}><h2>已到达策略决策</h2><p>{view.manifest.strategy?`${view.manifest.strategy} · 固定参数 ${JSON.stringify(view.manifest.parameters)}`:'当前会话只回放行情；选择策略后需创建新会话。'} · 仅目标决策，不是订单或成交。LONG=目标做多，FLAT=目标空仓；每根成熟闭合柱记录一次目标。</p><p>共 {view.decisions.length} 条，显示最近100条。预热期间没有决策；重置后记录随前缀清空。</p><div className="research-table"><table><thead><tr><th>可用时间 UTC</th><th>目标</th><th>柱开始 UTC</th><th>事件 ID</th></tr></thead><tbody>{view.decisions.slice(-100).map(event=><tr key={event.event_id}><td>{event.available_at}</td><td>{event.target==='LONG'?'做多目标':'空仓目标'}</td><td>{event.bar_open_time}</td><td title={event.event_id}>{event.event_id.slice(0,12)}</td></tr>)}</tbody></table></div><button disabled={busy||playing} onClick={()=>{if(!audit.current)return;const url=URL.createObjectURL(new Blob([JSON.stringify(audit.current,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`fc666-replay-prefix-${view.session_id}-${view.cursor}.json`;a.click();URL.revokeObjectURL(url);}}>下载已确认前缀</button></section>:null}
 <div ref={element} className="replay-canvas" data-testid="replay-chart" aria-label="已到达历史K线图"/>
 {view&&indicators?<p>仅当前前缀计算 SMA/EMA/Bollinger/VWAP、RSI/MACD/ATR、已确认结构；未成熟指标留空，不回填到过去。</p>:null}<p>图表技术由 TradingView Lightweight Charts 提供。</p></main>;
}
