"use client";
import {useEffect,useState} from 'react';
import {z} from 'zod';
const decimal=z.string().refine(value=>Number.isFinite(Number(value)));
function money(value:string|undefined){return value===undefined?'—':Number(value).toLocaleString('en-US',{maximumFractionDigits:8});}
const Row=z.object({job_id:z.uuid(),status:z.enum(['QUEUED','RUNNING','SUCCEEDED','FAILED','CANCELLED']),progress:z.number(),cancel_requested:z.boolean(),error:z.string().nullable(),run_id:z.string().nullable(),request:z.object({strategy:z.string(),parameters:z.record(z.string(),z.unknown()),as_of:z.string()}).passthrough(),metrics:z.object({net_pnl:decimal,total_return:decimal,max_drawdown:decimal,fees:decimal}).passthrough().nullable(),analysis:z.object({sharpe:z.number().finite().nullable(),closed_trade_count:z.number(),warnings:z.array(z.string()),unavailable_reasons:z.record(z.string(),z.string())}).nullable()});
const Batch=z.object({batch_id:z.uuid(),shared_sha256:z.string(),status:z.enum(['ACTIVE','COMPLETE']),trading_enabled:z.literal(false),jobs:z.array(Row).min(2).max(8)});
type Comparison=z.infer<typeof Batch>;
const KEY='fc666.research.batch.v1';
const EXAMPLE=JSON.stringify([{strategy:'ema_long_flat_v1',parameters:{period:10}},{strategy:'ema_long_flat_v1',parameters:{period:20}},{strategy:'sma_long_flat_v1',parameters:{fast:10,slow:20}}],null,2);
export default function BatchResearch({base}:{base:Record<string,unknown>}){
 const [variants,setVariants]=useState(EXAMPLE),[batchId,setBatchId]=useState<string|null>(null),[batch,setBatch]=useState<Comparison|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{const saved=localStorage.getItem(KEY);if(saved&&z.uuid().safeParse(saved).success){setBatchId(saved);setBusy(true);}},[]);
 useEffect(()=>{if(!batchId)return;const abort=new AbortController();let timer:ReturnType<typeof setTimeout>|undefined;
  async function poll(){try{const response=await fetch(`/api/research/batches/${batchId}`,{cache:'no-store',signal:abort.signal});if(response.status===404){localStorage.removeItem(KEY);setBatchId(null);setBusy(false);throw new Error('批次不存在');}if(!response.ok)throw new Error('批次状态不可用');const current=Batch.parse(await response.json());setBatch(current);setError('');setBusy(current.status==='ACTIVE');if(current.status==='ACTIVE')timer=setTimeout(poll,700);}catch(e){if(!abort.signal.aborted){setError(e instanceof Error?e.message:'批次连接失败');timer=setTimeout(poll,2000);}}}
  void poll();return()=>{abort.abort();if(timer)clearTimeout(timer);};
 },[batchId]);
 async function submit(){setBusy(true);setError('');setBatch(null);setBatchId(null);localStorage.removeItem(KEY);
  try{const parsed=JSON.parse(variants);if(!Array.isArray(parsed)||parsed.length<2||parsed.length>8)throw new Error('请输入2至8组参数');const response=await fetch('/api/research/batches',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({base,variants:parsed}),signal:AbortSignal.timeout(15000)});const data=await response.json();if(!response.ok)throw new Error(typeof data.detail==='string'?data.detail:'批次参数或历史数据不可用');const current=Batch.parse(data);setBatch(current);localStorage.setItem(KEY,current.batch_id);setBatchId(current.batch_id);}
  catch(e){setError(e instanceof Error?e.message:'批次提交失败');setBusy(false);}
 }
 async function cancel(){if(!batch)return;try{const response=await fetch(`/api/research/batches/${batch.batch_id}/cancel`,{method:'POST'});if(!response.ok)throw new Error('取消批次失败');setBatch(Batch.parse(await response.json()));}catch(e){setError(e instanceof Error?e.message:'取消失败');}}
 async function download(jobId:string){try{const response=await fetch(`/api/research/jobs/${jobId}/result`,{cache:'no-store'});if(!response.ok)throw new Error('结果不可用');const data=await response.json();if(data.trading_enabled!==false||typeof data.run_id!=='string')throw new Error('结果格式不可用');const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`fc666-${data.run_id}.json`;a.click();URL.revokeObjectURL(url);}catch(e){setError(e instanceof Error?e.message:'下载失败');}}
 return <section className="batch-research" data-testid="batch-research"><h2>参数批次研究</h2><p>使用上方交易对、周期、历史窗口、截止时间、资金、费用与滑点。一次固定数据及规则快照，提交2至8组参数；全部入队或全部拒绝。每项独立执行，失败或取消不影响其他已完成结果。</p><label>批次参数 JSON<textarea aria-label="批次参数 JSON" rows={12} value={variants} onChange={e=>setVariants(e.target.value)}/></label><button disabled={busy} onClick={()=>void submit()}>{busy?'批次计算中…':'提交参数批次'}</button>{batch?.status==='ACTIVE'?<button onClick={()=>void cancel()}>取消未完成项</button>:null}{error?<p role="alert">{error}</p>:null}
 {batch?<div data-testid="batch-comparison" data-status={batch.status}><p>批次 {batch.batch_id} · {batch.status==='ACTIVE'?'处理中':'全部结束'} · 固定截止 {batch.jobs[0].request.as_of}</p><p style={{overflowWrap:'anywhere'}}>共享快照 SHA256：{batch.shared_sha256}</p><p>所有收益为同一历史窗口的样本内描述；比较多组参数容易过拟合，未进行样本外验证，不构成收益预测。</p><div className="research-table"><table><thead><tr><th>策略与参数</th><th>状态</th><th>净收益 USDT</th><th>收益率</th><th>最大回撤</th><th>费用 USDT</th><th>Sharpe</th><th>完整交易</th><th>结果</th></tr></thead><tbody>{batch.jobs.map(row=><tr key={row.job_id}><td>{row.request.strategy}<br/>{JSON.stringify(row.request.parameters)}</td><td>{{QUEUED:'排队中',RUNNING:'计算中',SUCCEEDED:'已完成',FAILED:'失败',CANCELLED:'已取消'}[row.status]} {row.progress}%{row.cancel_requested?' · 已请求取消':''}{row.error?<p>{row.error}</p>:null}</td><td title={row.metrics?.net_pnl}>{money(row.metrics?.net_pnl)}</td><td>{row.metrics?`${(Number(row.metrics.total_return)*100).toFixed(4)}%`:'—'}</td><td>{row.metrics?`${(Number(row.metrics.max_drawdown)*100).toFixed(4)}%`:'—'}</td><td title={row.metrics?.fees}>{money(row.metrics?.fees)}</td><td title={row.analysis?.unavailable_reasons.sharpe}>{row.analysis?.sharpe===null?'不可用':row.analysis?.sharpe.toFixed(4)??'—'}</td><td>{row.analysis?.closed_trade_count??'—'}</td><td>{row.status==='SUCCEEDED'?<button onClick={()=>void download(row.job_id)}>下载完整结果</button>:null}{row.analysis?.warnings.map(warning=><small key={warning} style={{display:'block'}}>{warning}</small>)}</td></tr>)}</tbody></table></div></div>:null}</section>;
}
