"use client";
import {useEffect,useState} from 'react';
import {z} from 'zod';
const decimal=z.string().refine(value=>Number.isFinite(Number(value)));
const Segment=z.object({run_id:z.string(),manifest:z.object({start:z.string(),end:z.string(),bars:z.number(),parameters:z.record(z.string(),z.unknown())}).passthrough(),metrics:z.object({net_pnl:decimal,total_return:decimal,max_drawdown:decimal,fees:decimal,fill_count:z.number(),open_quantity:decimal}).passthrough(),analysis:z.object({sharpe:z.number().finite().nullable(),warnings:z.array(z.string()),unavailable_reasons:z.record(z.string(),z.string())}).passthrough()}).passthrough();
const Result=z.object({run_id:z.string(),trading_enabled:z.literal(false),manifest:z.object({engine_version:z.literal('spot-holdout-v1'),split_at:z.string(),policy:z.literal('cold-start-independent-v1'),strategy:z.string(),parameters:z.record(z.string(),z.unknown()),assumptions:z.array(z.string())}).passthrough(),train:Segment,test:Segment}).passthrough();
const Job=z.object({job_id:z.uuid(),status:z.enum(['QUEUED','RUNNING','SUCCEEDED','FAILED','CANCELLED']),progress:z.number(),cancel_requested:z.boolean(),error:z.string().nullable(),request:z.object({research_type:z.literal('holdout'),symbol:z.string(),timeframe:z.string(),train_bars:z.number(),as_of:z.string()}).passthrough()});
type Task=z.infer<typeof Job>;
const KEY='fc666.research.holdout.v1';
export default function HoldoutResearch({base}:{base:Record<string,unknown>}){
 const [trainBars,setTrainBars]=useState('60'),[jobId,setJobId]=useState<string|null>(null),[job,setJob]=useState<Task|null>(null),[history,setHistory]=useState<Task[]>([]),[run,setRun]=useState<z.infer<typeof Result>|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function loadHistory(){try{const response=await fetch('/api/research/jobs',{cache:'no-store'});if(response.ok){const records=z.array(z.unknown()).parse(await response.json());setHistory(records.flatMap(record=>{const parsed=Job.safeParse(record);return parsed.success?[parsed.data]:[];}));}}catch{/* Retain observed history on transport failure. */}}
 useEffect(()=>{const saved=localStorage.getItem(KEY);if(saved&&z.uuid().safeParse(saved).success){setJobId(saved);setBusy(true);}void loadHistory();},[]);
 useEffect(()=>{if(!jobId)return;const abort=new AbortController();let timer:ReturnType<typeof setTimeout>|undefined;
  async function poll(){try{const response=await fetch(`/api/research/jobs/${jobId}`,{cache:'no-store',signal:abort.signal});if(response.status===404){setBusy(false);setJobId(null);localStorage.removeItem(KEY);setError('分段任务不存在');return;}if(!response.ok)throw new Error('分段任务状态不可用');const current=Job.parse(await response.json());setJob(current);setError('');if(current.status==='SUCCEEDED'){const result=await fetch(`/api/research/jobs/${jobId}/result`,{cache:'no-store',signal:abort.signal});if(!result.ok)throw new Error('分段结果不可用');setRun(Result.parse(await result.json()));setBusy(false);void loadHistory();}else if(['FAILED','CANCELLED'].includes(current.status)){setRun(null);setBusy(false);if(current.status==='FAILED')setError(current.error??'任务失败');void loadHistory();}else timer=setTimeout(poll,700);}catch(e){if(!abort.signal.aborted){setError(e instanceof Error?e.message:'分段任务连接失败');timer=setTimeout(poll,2000);}}}
  void poll();return()=>{abort.abort();if(timer)clearTimeout(timer);};
 },[jobId]);
 async function submit(){setBusy(true);setError('');setRun(null);setJob(null);setJobId(null);localStorage.removeItem(KEY);
  try{const response=await fetch('/api/research/holdouts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({base,train_bars:Number(trainBars)}),signal:AbortSignal.timeout(15000)});const data=await response.json();if(!response.ok)throw new Error(typeof data.detail==='string'?data.detail:'分段参数或历史数据不可用');const current=Job.parse(data);setJob(current);localStorage.setItem(KEY,current.job_id);setJobId(current.job_id);void loadHistory();}catch(e){setError(e instanceof Error?e.message:'提交失败');setBusy(false);}
 }
 async function cancel(){if(!job)return;try{const response=await fetch(`/api/research/jobs/${job.job_id}/cancel`,{method:'POST'});if(!response.ok)throw new Error('分段任务已结束或无法取消');setJob(Job.parse(await response.json()));}catch(e){setError(e instanceof Error?e.message:'取消失败');}}
 function restore(item:Task){setRun(null);setError('');setJob(item);setBusy(!['SUCCEEDED','FAILED','CANCELLED'].includes(item.status));localStorage.setItem(KEY,item.job_id);setJobId(null);setTimeout(()=>setJobId(item.job_id),0);}
 return <section className="batch-research" data-testid="holdout-research"><h2>样本内 / 样本外分段研究</h2><p>使用上方策略、固定参数及历史窗口，按时间顺序切分。两段各用独立初始资金、空仓和全新指标状态；预热期保持空仓，前一段的持仓及待成交信号不会带入后一段。每段至少包含策略预热周期加1根。</p><p>这里不训练或选择参数。反复查看样本外结果再调参数会污染留出样本；分段比较不代表统计验证或收益预测。</p><label>样本内柱数 <input aria-label="样本内柱数" required type="number" min="2" max="998" value={trainBars} onChange={e=>setTrainBars(e.target.value)}/></label><button disabled={busy} onClick={()=>void submit()}>{busy?'分段计算中…':'运行分段研究'}</button>
 {job?<div data-testid="holdout-task" data-status={job.status}><p>{{QUEUED:'排队中',RUNNING:'计算中',SUCCEEDED:'已完成',FAILED:'失败',CANCELLED:'已取消'}[job.status]} · {job.progress}%{job.cancel_requested?' · 已请求取消':''} · {job.request.symbol} · {job.request.timeframe} · 固定截止 {job.request.as_of}</p>{['QUEUED','RUNNING'].includes(job.status)?<button disabled={job.cancel_requested} onClick={()=>void cancel()}>取消分段任务</button>:null}</div>:null}
 <details><summary>最近分段任务</summary><button onClick={()=>void loadHistory()}>刷新分段记录</button><ul>{history.map(item=><li key={item.job_id}><button onClick={()=>restore(item)}>{item.request.symbol} · {item.request.timeframe} · {item.status} · {item.job_id.slice(0,8)}</button></li>)}</ul></details>{error?<p role="alert">{error}</p>:null}
 {run?<div data-testid="holdout-comparison"><p>固定策略 {run.manifest.strategy} · 参数 {JSON.stringify(run.manifest.parameters)} · 分界 UTC {run.manifest.split_at}</p><div className="research-table"><table><thead><tr><th>区间</th><th>UTC 起止（结束不含）</th><th>柱数</th><th>净收益 USDT</th><th>收益率</th><th>最大回撤</th><th>Sharpe</th><th>成交次数</th><th>结束持仓</th></tr></thead><tbody>{([['样本内',run.train],['样本外',run.test]] as const).map(([label,segment])=><tr key={label}><td>{label}</td><td>{segment.manifest.start}<br/>{segment.manifest.end}</td><td>{segment.manifest.bars}</td><td title={segment.metrics.net_pnl}>{Number(segment.metrics.net_pnl).toLocaleString('en-US',{maximumFractionDigits:8})}</td><td>{(Number(segment.metrics.total_return)*100).toFixed(4)}%</td><td>{(Number(segment.metrics.max_drawdown)*100).toFixed(4)}%</td><td title={segment.analysis.unavailable_reasons.sharpe}>{segment.analysis.sharpe===null?'不可用':segment.analysis.sharpe.toFixed(4)}</td><td>{segment.metrics.fill_count}</td><td>{segment.metrics.open_quantity}</td></tr>)}</tbody></table></div><p>两段独立资金，收益不能相加或拼成一条账户权益曲线。结束持仓按该段最后收盘价标记，不强制清仓。</p><details><summary>分段运行清单</summary><p style={{overflowWrap:'anywhere'}}>run_id: {run.run_id}</p><ul>{run.manifest.assumptions.map(assumption=><li key={assumption}>{assumption}</li>)}</ul></details><button onClick={()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(run,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`fc666-holdout-${run.run_id}.json`;a.click();URL.revokeObjectURL(url);}}>下载完整分段结果</button></div>:null}</section>;
}
