"use client";
import {useEffect,useState} from 'react';
import {z} from 'zod';
const Status=z.enum(['READY','ENDED','RUNNING','PAUSED','STOPPED','BLOCKED','LIMIT_REACHED']);
const List=z.object({items:z.array(z.object({session_id:z.uuid(),symbol:z.string(),timeframe:z.string(),status:Status,revision:z.number().int(),integrity:z.enum(['VERIFIED','INVALID']),created_at:z.string(),account:z.object({cash:z.string(),quantity:z.string(),equity:z.string()}).nullable()})),next_cursor:z.string().nullable(),trading_enabled:z.literal(false)});
const Controls=z.object({items:z.array(z.object({event_id:z.uuid(),recorded_at:z.string(),action:z.string(),count:z.number().int(),expected_revision:z.number().int(),before_revision:z.number().int(),after_revision:z.number().int(),outcome:z.enum(['APPLIED','NOOP','CONFLICT']),actor:z.literal('UNAUTHENTICATED_LOCAL')})),next_cursor:z.string().nullable(),trading_enabled:z.literal(false),coverage:z.literal('CONTROL_REQUESTS_SINCE_SCHEMA_0008')});
const labels:Record<string,string>={READY:'可推进',ENDED:'历史已结束',RUNNING:'运行中',PAUSED:'已暂停',STOPPED:'已停止',BLOCKED:'已阻断',LIMIT_REACHED:'已达上限',APPLIED:'已执行',NOOP:'状态未变化',CONFLICT:'版本冲突',step:'推进',reset:'重置',halt:'停止买入',pause:'暂停',resume:'恢复',stop:'停止账户'};

export function AccountList({kind,selected,busy,revision,onSelect}:{kind:'sessions'|'streams';selected?:string;busy:boolean;revision?:number;onSelect:(id:string)=>Promise<void>}){
 const [status,setStatus]=useState(''),[cursor,setCursor]=useState<string|null>(null),[data,setData]=useState<z.infer<typeof List>|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[refresh,setRefresh]=useState(0);
 useEffect(()=>{const abort=new AbortController();setLoading(true);setError('');setData(null);const query=new URLSearchParams({limit:'10'});if(status)query.set('status',status);if(cursor)query.set('cursor',cursor);
 void fetch(`/api/paper/${kind}?${query}`,{cache:'no-store',signal:abort.signal}).then(async response=>{if(!response.ok)throw new Error();return List.parse(await response.json());}).then(value=>{if(!abort.signal.aborted)setData(value);}).catch(()=>{if(!abort.signal.aborted)setError('账户列表读取失败，请重试');}).finally(()=>{if(!abort.signal.aborted)setLoading(false);});return()=>abort.abort();},[kind,status,cursor,refresh,selected,revision]);
 const options=kind==='sessions'?['READY','ENDED']:['RUNNING','PAUSED','STOPPED','BLOCKED','LIMIT_REACHED'];
 return <section data-testid="paper-accounts"><h2>已有模拟账户</h2><label>账户状态筛选<select aria-label="账户状态筛选" value={status} onChange={event=>{setStatus(event.target.value);setCursor(null);}}><option value="">全部状态</option>{options.map(value=><option key={value} value={value}>{labels[value]}</option>)}</select></label> <button disabled={loading} onClick={()=>setRefresh(value=>value+1)}>刷新账户列表</button>{error?<p role="alert">{error}</p>:null}{loading?<p>正在读取账户列表…</p>:null}<div className="research-table"><table><thead><tr><th>账户 / 创建 UTC</th><th>行情</th><th>状态</th><th>现金 / 库存</th><th>选择</th></tr></thead><tbody>{data?.items.map(item=><tr key={item.session_id} data-account-id={item.session_id}><td style={{overflowWrap:'anywhere'}}>{item.session_id}<br/>{item.created_at}</td><td>{item.symbol} · {item.timeframe}</td><td>{labels[item.status]} · v{item.revision}{item.integrity==='INVALID'?<strong> · 账本核对失败</strong>:null}</td><td>{item.account?`${item.account.cash} / ${item.account.quantity}`:'余额未确认'}</td><td><button disabled={busy||selected===item.session_id||item.integrity==='INVALID'} onClick={()=>void onSelect(item.session_id)}>{selected===item.session_id?'当前账户':'查看账户'}</button></td></tr>)}</tbody></table></div>{data?.items.length===0?<p>此筛选下没有账户。</p>:null}<button disabled={loading||cursor===null} onClick={()=>setCursor(null)}>返回首批账户</button> <button disabled={loading||!data?.next_cursor} onClick={()=>setCursor(data?.next_cursor??null)}>下一批账户</button><p>已停止账户保留资金与库存。选择账户只读取状态；当前环境尚无多用户鉴权。</p></section>;
}

export function ControlHistory({kind,id,revision}:{kind:'sessions'|'streams';id:string;revision:number}){
 const [cursor,setCursor]=useState<string|null>(null),[data,setData]=useState<z.infer<typeof Controls>|null>(null),[error,setError]=useState(''),[refresh,setRefresh]=useState(0),[loading,setLoading]=useState(false);
 useEffect(()=>{const abort=new AbortController();setData(null);setError('');setLoading(true);const query=new URLSearchParams({limit:'10'});if(cursor)query.set('cursor',cursor);void fetch(`/api/paper/${kind}/${id}/controls?${query}`,{cache:'no-store',signal:abort.signal}).then(async response=>{if(!response.ok)throw new Error();return Controls.parse(await response.json());}).then(value=>{if(!abort.signal.aborted)setData(value);}).catch(()=>{if(!abort.signal.aborted)setError('控制记录读取失败，请重试');}).finally(()=>{if(!abort.signal.aborted)setLoading(false);});return()=>abort.abort();},[kind,id,revision,cursor,refresh]);
 return <section data-testid="paper-controls"><h2>控制操作记录</h2><p>记录自此功能上线后的服务器处理结果。调用者未鉴权；记录不证明用户身份或浏览器已收到响应。早期操作及自动行情推进不在此列表。</p><button disabled={loading} onClick={()=>setRefresh(value=>value+1)}>刷新控制记录</button>{error?<p role="alert">{error}</p>:null}<div className="research-table"><table><thead><tr><th>服务器时间 UTC</th><th>操作</th><th>处理结果</th><th>请求版本</th><th>前后版本</th></tr></thead><tbody>{data?.items.map(item=><tr key={item.event_id}><td>{item.recorded_at}</td><td>{labels[item.action]??item.action} ×{item.count}</td><td>{labels[item.outcome]}</td><td>{item.expected_revision}</td><td>{item.before_revision} → {item.after_revision}</td></tr>)}</tbody></table></div>{data?.items.length===0?<p>暂无控制记录。</p>:null}<button disabled={loading||cursor===null} onClick={()=>setCursor(null)}>返回最新记录</button> <button disabled={loading||!data?.next_cursor} onClick={()=>setCursor(data?.next_cursor??null)}>更早控制记录</button></section>;
}
