"use client";
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {z} from 'zod';
import {AccountList,ControlHistory} from './accounts';
import {CandleSchema,Symbols,Intervals} from '../../lib/market';
const Decimal=z.string().regex(/^-?\d+(\.\d+)?([Ee][+-]?\d+)?$/);
const Timestamp=z.iso.datetime({offset:true});
const Config=z.object({initial_cash:Decimal,fee_rate:Decimal,slippage_rate:Decimal,allocation:Decimal,participation:Decimal,period:z.number().int()});
const Limits=z.object({max_order_quote:Decimal,max_position_quote:Decimal,max_drawdown:Decimal});
const Order=z.object({order_id:z.string().regex(/^[0-9a-f]{64}$/),side:z.enum(['BUY','SELL']),decision_at:Timestamp,execution_at:Timestamp,simulated:z.literal(true),status:z.enum(['FILLED','PARTIAL_CANCELLED','REJECTED']),reason:z.string().optional(),quantity:Decimal.optional()});
const Fill=z.object({order_id:z.string(),side:z.enum(['BUY','SELL']),decision_at:Timestamp,execution_at:Timestamp,simulated:z.literal(true),quantity:Decimal,price:Decimal,fee:Decimal,realized_pnl:Decimal,reference_open:Decimal,cash_after:Decimal,quantity_after:Decimal});
const State=z.object({session_id:z.uuid(),revision:z.number().int().nonnegative(),cursor:z.number().int().nonnegative(),total:z.number().int().min(2).max(1000),status:z.enum(['READY','ENDED']),clock:Timestamp,trading_enabled:z.literal(false),mode:z.literal('HISTORICAL_PAPER'),manifest:z.object({version:z.literal('spot-paper-next-open-v1'),snapshot_sha256:z.string().regex(/^[0-9a-f]{64}$/),symbol:z.enum(Symbols),timeframe:z.enum(Intervals),as_of:Timestamp,start:Timestamp,end:Timestamp,strategy:z.enum(['ema_long_flat_v1','sma_long_flat_v1']),strategy_version:z.literal(1),parameters:z.record(z.string(),z.unknown()),config:Config,risk:Limits,instrument:z.record(z.string(),z.unknown())}),candles:z.array(CandleSchema),account:z.object({cash:Decimal,quantity:Decimal,cost_basis:Decimal,equity:Decimal,realized_pnl:Decimal,unrealized_pnl:Decimal,net_pnl:Decimal,fees:Decimal,peak_equity:Decimal,max_drawdown:Decimal}),risk:z.object({entry_halted:z.boolean(),drawdown_halted:z.boolean(),manual_halt_at:z.number().int().nonnegative().nullable(),events:z.array(z.object({reason:z.literal('MAX_DRAWDOWN'),available_at:Timestamp,drawdown:Decimal}))}),orders:z.array(Order),fills:z.array(Fill),equity:z.array(z.object({as_of:Timestamp,cash:Decimal,quantity:Decimal,equity:Decimal})),signals:z.array(z.object({target:z.enum(['LONG','FLAT']),available_at:Timestamp})),pending:z.object({target:z.enum(['LONG','FLAT']),available_at:Timestamp,status:z.enum(['AWAIT_NEXT_REACHED_BAR','NO_NEXT_BAR'])}).nullable()}).superRefine((state,context)=>{
 const clock=Date.parse(state.clock);
 if(state.cursor>state.total||state.candles.length!==state.cursor||state.equity.length!==state.cursor||state.candles.some(bar=>!bar.is_closed||Date.parse(bar.close_time)>clock)||state.orders.some(order=>Date.parse(order.execution_at)>clock||Date.parse(order.decision_at)>Date.parse(order.execution_at))||state.fills.some(fill=>Date.parse(fill.execution_at)>clock)||state.signals.some(signal=>Date.parse(signal.available_at)>clock)||state.risk.events.some(event=>Date.parse(event.available_at)>clock)||state.equity.some(point=>Date.parse(point.as_of)>clock)||(state.pending!==null&&Date.parse(state.pending.available_at)>clock))context.addIssue({code:'custom',message:'Invalid or future paper data'});
});
type View=z.infer<typeof State>;
const KEY='fc666.paper.session.v1';
const reasons:Record<string,string>={MANUAL_HALT:'手动停止买入',MAX_DRAWDOWN:'回撤限制已触发',MAX_ORDER_QUOTE:'超出单笔买入金额',MAX_POSITION_QUOTE:'超出持仓金额',MARKET_RULES_OR_CAPACITY:'数量/金额规则或容量不足',NONPOSITIVE_PRICE:'价格规则不允许成交'};
// Number conversion is display only; API ledger and export keep exact decimal strings.
const money=(value:string)=>Number(value).toLocaleString('zh-CN',{maximumFractionDigits:2,minimumFractionDigits:2});
export default function Paper(){
 const [symbol,setSymbol]=useState('BTCUSDT'),[timeframe,setTimeframe]=useState('1h'),[limit,setLimit]=useState('120'),[period,setPeriod]=useState('20'),[strategy,setStrategy]=useState('ema_long_flat_v1'),[fast,setFast]=useState('10'),[slow,setSlow]=useState('20'),[cutoff,setCutoff]=useState('');
 const [cash,setCash]=useState('10000'),[fee,setFee]=useState('0.001'),[slippage,setSlippage]=useState('0.0005'),[allocation,setAllocation]=useState('0.5'),[participation,setParticipation]=useState('0.01'),[maxOrder,setMaxOrder]=useState('5000'),[maxPosition,setMaxPosition]=useState('10000'),[maxDrawdown,setMaxDrawdown]=useState('0.2');
 const [view,setView]=useState<View|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const current=useRef<View|null>(null),locked=useRef(false),raw=useRef<Record<string,unknown>|null>(null);
 function adopt(data:Record<string,unknown>){const next=State.parse(data);current.current=next;raw.current=data;setView(next);localStorage.setItem(KEY,next.session_id);return next;}
 function restore(next:View){const m=next.manifest,c=m.config,r=m.risk;setSymbol(m.symbol);setTimeframe(m.timeframe);setLimit(String(next.total));setPeriod(String(c.period));setStrategy(m.strategy);setFast(String(m.parameters.fast??10));setSlow(String(m.parameters.slow??20));setCutoff(m.as_of);setCash(c.initial_cash);setFee(c.fee_rate);setSlippage(c.slippage_rate);setAllocation(c.allocation);setParticipation(c.participation);setMaxOrder(r.max_order_quote);setMaxPosition(r.max_position_quote);setMaxDrawdown(r.max_drawdown);}
 async function read(id:string,signal?:AbortSignal){const response=await fetch(`/api/paper/sessions/${id}`,{cache:'no-store',signal:signal??AbortSignal.timeout(15000)});if(response.status===404){localStorage.removeItem(KEY);throw new Error('模拟账户不存在');}if(!response.ok)throw new Error('模拟账户状态不可用');return await response.json();}
 useEffect(()=>{const id=localStorage.getItem(KEY);if(!id||!z.uuid().safeParse(id).success)return;const abort=new AbortController();locked.current=true;setBusy(true);void read(id,abort.signal).then(data=>{if(!abort.signal.aborted)restore(adopt(data));}).catch(e=>{if(!abort.signal.aborted)setError(e instanceof Error?e.message:'恢复失败');}).finally(()=>{if(!abort.signal.aborted){locked.current=false;setBusy(false);}});return()=>abort.abort();},[]);
 async function selectAccount(id:string){if(locked.current)return;locked.current=true;setBusy(true);setError('');try{const data=await read(id);if(data.session_id!==id)throw new Error('账户不一致');restore(adopt(data));}catch{setError('选择账户失败，保留最后确认账本');}finally{locked.current=false;setBusy(false);}}
 async function create(event:FormEvent){event.preventDefault();if(locked.current)return;locked.current=true;setBusy(true);setError('');current.current=null;raw.current=null;setView(null);localStorage.removeItem(KEY);
  try{const response=await fetch('/api/paper/sessions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({symbol,timeframe,limit:Number(limit),as_of:cutoff||null,strategy,parameters:strategy==='ema_long_flat_v1'?{period:Number(period)}:{fast:Number(fast),slow:Number(slow)},config:{initial_cash:cash,fee_rate:fee,slippage_rate:slippage,allocation,participation,period:Number(period)},risk:{max_order_quote:maxOrder,max_position_quote:maxPosition,max_drawdown:maxDrawdown}}),signal:AbortSignal.timeout(15000)});const data=await response.json();if(!response.ok)throw new Error(typeof data.detail==='string'?data.detail:'模拟账户参数或历史数据不可用');adopt(data);}
  catch(e){setError(e instanceof Error?e.message:'创建失败');}finally{locked.current=false;setBusy(false);}
 }
 async function command(action:'step'|'reset'|'halt'){
  let failure='操作未确认，已尝试同步服务器进度';
  const before=current.current;if(!before||locked.current)return;locked.current=true;setBusy(true);setError('');
  try{const response=await fetch(`/api/paper/sessions/${before.session_id}/command`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({expected_revision:before.revision,action,count:1}),signal:AbortSignal.timeout(15000)});if(!response.ok){if(response.status===409)failure='账户版本冲突，已尝试同步服务器进度';throw new Error(failure);}const data=await response.json();const next=State.parse(data);if(next.session_id!==before.session_id||next.manifest.snapshot_sha256!==before.manifest.snapshot_sha256)throw new Error('模拟账户快照不一致');adopt(data);}
  catch{setError(failure);try{adopt(await read(before.session_id));}catch{/* Keep acknowledged account; never retry a command automatically. */}}
  finally{locked.current=false;setBusy(false);}
 }
 return <main className="research-page paper-page"><header><strong>FC666 · Paper</strong><a href="/">行情终端</a><a href="/portfolio">模拟组合</a><a href="/research">研究</a><a href="/replay">回放</a><a href="/paper/realtime">实时模拟</a><span className="badge">历史模拟 · 实盘关闭</span></header><h1>现货模拟账户</h1><p>独立资金与持仓，使用固定历史快照。收盘目标在下一根已到达柱开盘模拟成交；无交易所下单。这里只支持历史做多/空仓，不含杠杆或手动订单；实时闭合柱模拟请使用“实时模拟”入口。</p>
 <AccountList kind="sessions" selected={view?.session_id} revision={view?.revision} busy={busy} onSelect={selectAccount}/>
 <form onSubmit={create} className="research-form"><label>模拟策略<select aria-label="模拟策略" value={strategy} onChange={e=>setStrategy(e.target.value)}><option value="ema_long_flat_v1">EMA Long / Flat v1</option><option value="sma_long_flat_v1">SMA Long / Flat v1</option></select></label><label>模拟交易对<select aria-label="模拟交易对" value={symbol} onChange={e=>setSymbol(e.target.value)}>{Symbols.map(s=><option key={s}>{s}</option>)}</select></label><label>模拟周期<select aria-label="模拟周期" value={timeframe} onChange={e=>setTimeframe(e.target.value)}>{Intervals.map(t=><option key={t}>{t}</option>)}</select></label><label>模拟柱数<input required type="number" min="2" max="1000" value={limit} onChange={e=>setLimit(e.target.value)}/></label><label>模拟均线周期<input required type="number" min="2" max="500" value={period} onChange={e=>setPeriod(e.target.value)}/></label>{strategy==='sma_long_flat_v1'?<><label>模拟 SMA 快周期<input required type="number" min="2" max="499" value={fast} onChange={e=>setFast(e.target.value)}/></label><label>模拟 SMA 慢周期<input required type="number" min={Number(fast)+1} max="500" value={slow} onChange={e=>setSlow(e.target.value)}/></label></>:null}<label>初始资金 USDT<input required inputMode="decimal" value={cash} onChange={e=>setCash(e.target.value)}/></label><label>单笔买入上限 USDT<input required inputMode="decimal" value={maxOrder} onChange={e=>setMaxOrder(e.target.value)}/></label><label>买入后持仓上限 USDT<input required inputMode="decimal" value={maxPosition} onChange={e=>setMaxPosition(e.target.value)}/></label><label>回撤停止阈值（0..1）<input required inputMode="decimal" value={maxDrawdown} onChange={e=>setMaxDrawdown(e.target.value)}/></label><label>买入资金比例（0..1）<input required inputMode="decimal" value={allocation} onChange={e=>setAllocation(e.target.value)}/></label><label>前柱成交量参与率（0..0.1）<input required inputMode="decimal" value={participation} onChange={e=>setParticipation(e.target.value)}/></label><label>手续费率<input required inputMode="decimal" value={fee} onChange={e=>setFee(e.target.value)}/></label><label>滑点率<input required inputMode="decimal" value={slippage} onChange={e=>setSlippage(e.target.value)}/></label><label>模拟截止时间（含时区，可空）<input value={cutoff} onChange={e=>setCutoff(e.target.value)}/></label><button type="submit" disabled={busy}>创建独立模拟账户</button></form>
 {error?<p role="alert">{error}</p>:null}
 {view?<section data-testid="paper-state" data-cursor={view.cursor} data-revision={view.revision} data-halted={view.risk.entry_halted} data-fills={view.fills.length}><h2>{view.manifest.symbol} · {view.manifest.timeframe} · {view.cursor}/{view.total} 根</h2><p>模拟时钟 UTC：<time>{view.clock}</time> · {view.status==='ENDED'?'历史已结束':'手动推进'} · <strong className={view.risk.entry_halted?'warning':'buy'}>{view.risk.entry_halted?'新买入已停止':'允许策略买入'}</strong></p><div className="replay-controls"><button disabled={busy||view.status==='ENDED'} onClick={()=>void command('step')}>推进模拟一根</button><button disabled={busy||view.risk.manual_halt_at!==null} onClick={()=>void command('halt')}>停止新买入</button><button disabled={busy} onClick={()=>void command('reset')}>重置资金并从头模拟</button><button disabled={busy} onClick={()=>{if(!raw.current)return;const url=URL.createObjectURL(new Blob([JSON.stringify(raw.current,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`fc666-paper-prefix-${view.session_id}-${view.cursor}.json`;a.click();URL.revokeObjectURL(url);}}>下载模拟账本前缀</button></div><p>停止只禁止后续买入，仍允许策略卖出；不会自动平仓。重置清空本次资金、持仓和停止状态，使用原固定参数重新模拟。</p>
 <div className="research-metrics">{[['现金 USDT',view.account.cash],['账户权益 USDT',view.account.equity],['持仓数量',view.account.quantity],['已实现盈亏 USDT',view.account.realized_pnl],['未实现盈亏 USDT',view.account.unrealized_pnl],['累计手续费 USDT',view.account.fees]].map(([label,value])=><div key={label}><small>{label}</small><strong title={value}>{label==='持仓数量'?value:money(value)}</strong></div>)}</div><p>金额显示到小数后2位，账本下载保留完整精度。成交 {view.fills.length} 笔 · 最大观测回撤 {(Number(view.account.max_drawdown)*100).toFixed(2)}% · 待处理目标：{view.pending?`${view.pending.target}，${view.pending.status==='NO_NEXT_BAR'?'末尾无下一根，不再成交':'等待下一根'}`:'预热中'}</p>
 <details><summary>本账户固定参数与模拟假设</summary><p>{view.manifest.strategy} · {JSON.stringify(view.manifest.parameters)} · 初始资金 {view.manifest.config.initial_cash} USDT</p><p>单笔买入上限 {view.manifest.risk.max_order_quote} · 买入后持仓上限 {view.manifest.risk.max_position_quote} · 回撤停止阈值 {view.manifest.risk.max_drawdown}</p><p>资金比例 {view.manifest.config.allocation} · 前柱量参与率 {view.manifest.config.participation} · 费率 {view.manifest.config.fee_rate} · 滑点率 {view.manifest.config.slippage_rate}</p><p>成交容量为前一闭合柱成交量的比例代理，不代表真实开盘流动性。市价成交按不利滑点与价格/数量规则取整，部分成交余量取消。末尾目标不强制成交，不强制平仓。持仓上限只在买入时检查，涨价可能超过上限；回撤按已到达开盘与收盘观察，不是柱内止损。</p><p>修改上方表单只影响新账户。刷新恢复已确认资金和进度；冲突或丢失响应只读取服务器状态，不自动重发操作。当前服务无多用户权限隔离。</p><p>固定截止 {view.manifest.as_of} · SHA256 {view.manifest.snapshot_sha256}</p></details>
 <h2>模拟成交 · 最近100笔</h2><div className="research-table"><table><thead><tr><th>执行时间 UTC</th><th>方向</th><th>数量</th><th>价格</th><th>手续费</th><th>已实现盈亏</th></tr></thead><tbody>{view.fills.slice(-100).map(fill=><tr key={fill.order_id}><td>{fill.execution_at}</td><td className={fill.side==='BUY'?'buy':'sell'}>{fill.side==='BUY'?'买入':'卖出'}</td><td>{fill.quantity}</td><td>{fill.price}</td><td>{money(fill.fee)}</td><td>{money(fill.realized_pnl)}</td></tr>)}</tbody></table></div>
 <h2>模拟订单 · 最近100条</h2><div className="research-table"><table><thead><tr><th>执行时间 UTC</th><th>方向</th><th>状态</th><th>数量 / 拒绝原因</th></tr></thead><tbody>{view.orders.slice(-100).map(order=><tr key={order.order_id}><td>{order.execution_at}</td><td>{order.side==='BUY'?'买入':'卖出'}</td><td>{order.status==='REJECTED'?'已拒绝':order.status==='PARTIAL_CANCELLED'?'部分成交，余量取消':'全部成交'}</td><td>{order.reason?(reasons[order.reason]??order.reason):order.quantity}</td></tr>)}</tbody></table></div>{view.risk.events.map(event=><p className="warning" key={event.available_at}>回撤停止触发：{event.available_at} · {(Number(event.drawdown)*100).toFixed(2)}%</p>)}</section>:<p>创建账户后从零根开始，所有成交由已到达历史与冻结规则计算。</p>}{view?<ControlHistory key={view.session_id} kind="sessions" id={view.session_id} revision={view.revision}/>:null}</main>;
}
