'use client';
import {useEffect,useRef,useState} from 'react';
import {z} from 'zod';
const reservationSchema=z.object({reserved_cash:z.string(),reserved_quantity:z.string(),flows:z.array(z.object({order_id:z.string()}))});
const batchSchema=z.object({preparation_id:z.string(),status:z.string(),coverage:z.enum(['VERIFIED','LEGACY_UNAVAILABLE']),reservation:reservationSchema.nullable(),outcome:z.object({economic_effects_applied:z.boolean()}).nullable()});
const schema=z.object({version:z.literal('paper-projected-funding-v1'),session_id:z.uuid(),total_batches:z.number().int().nonnegative(),window_limit:z.literal(20),has_older:z.boolean(),reserved_cash:z.string().nullable(),reserved_quantity:z.string().nullable(),available_cash:z.string().nullable(),available_quantity:z.string().nullable(),trading_enabled:z.literal(false),external_submission_supported:z.literal(false),batches:z.array(batchSchema)});
type Report=z.infer<typeof schema>;
const states:Record<string,string>={PREPARED:'等待消费',CONSUMED:'已结算',CANCELLED:'已取消'};
export default function Funding({id,disabled}:{id:string;disabled:boolean}){
 const [value,setValue]=useState<Report|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');const request=useRef<AbortController|null>(null);
 useEffect(()=>()=>request.current?.abort(),[]);
 async function inspect(){request.current?.abort();const controller=new AbortController();request.current=controller;setBusy(true);setValue(null);setError('');try{const response=await fetch(`/api/paper/streams/${id}/funding`,{cache:'no-store',signal:controller.signal});if(!response.ok)throw Error(`资金预留核对未确认 (${response.status})`);const parsed=schema.parse(await response.json());if(parsed.session_id!==id)throw Error('账户不一致');setValue(parsed);}catch(e){if(!controller.signal.aborted)setError(String(e));}finally{if(!controller.signal.aborted)setBusy(false);}}
 return <section data-testid="paper-funding"><h2>模拟账户资金预留</h2><p>准备批次先保存预计成交资金和库存预留；成交与结算一起保存，取消释放预留。现金账面余额不会在准备时扣除，此处展示扣除当前已知预留后的可用量。预留仅覆盖本账户已授权的预计模拟成交，不是完整订单需求或共享资金。</p><button disabled={busy||disabled} onClick={()=>void inspect()}>核对模拟资金预留</button>{error?<p role="alert">{error}</p>:null}{value?<div data-testid="funding-result"><p>当前预留现金 {value.reserved_cash??'未知'} USDT / 库存 {value.reserved_quantity??'未知'}；可用现金 {value.available_cash??'历史待处理批次无预留证据'} / 可用库存 {value.available_quantity??'未知'}。</p><p>共保存 {value.total_batches} 批次；本次仅核对最新20批次{value.has_older?'，更早记录不在本次范围':''}。旧记录不补造资金预留。</p>{value.batches.length?<div className="research-table"><table><thead><tr><th>准备编号</th><th>状态 / 覆盖</th><th>批次预留现金 / 库存</th><th>结算</th></tr></thead><tbody>{value.batches.map(batch=><tr key={batch.preparation_id}><td style={{overflowWrap:'anywhere'}}>{batch.preparation_id}</td><td>{states[batch.status]??batch.status} / {batch.coverage==='VERIFIED'?'已核对':'无历史证据'}</td><td>{batch.reservation?`${batch.reservation.reserved_cash} / ${batch.reservation.reserved_quantity}`:'无历史证据'}</td><td>{batch.outcome?(batch.outcome.economic_effects_applied?'成交已结算':batch.status==='CANCELLED'?'取消已释放':'无成交，批次已处理'):'未结算或历史不可用'}</td></tr>)}</tbody></table></div>:<p>此账户尚无准备批次。</p>}<p>只读检查，不执行成交、撤单或恢复；实盘关闭。</p></div>:null}</section>;
}
