'use client';
import {useEffect,useRef,useState} from 'react';
import {z} from 'zod';
const schema=z.object({version:z.literal('paper-completed-order-intent-v1'),session_id:z.uuid(),as_of:z.string(),coverage:z.enum(['LEGACY_UNMATERIALIZED','VERIFIED']),ledger_orders:z.number().int().nonnegative(),durable_orders:z.number().int().nonnegative(),trading_enabled:z.literal(false),automatic_replay:z.literal(false),in_flight_submission_supported:z.literal(false),inputs_sha256:z.string(),intents:z.array(z.object({intent_id:z.string(),origin:z.enum(['BAR_ACCEPTANCE','HISTORICAL_MATERIALIZATION']),recorded_at:z.string(),status:z.enum(['FILLED','PARTIAL_CANCELLED','REJECTED']),transitions:z.array(z.string())}))});
type Report=z.infer<typeof schema>;
export default function Intents({id,disabled}:{id:string;disabled:boolean}){
 const [value,setValue]=useState<Report|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');const raw=useRef<unknown>(null),request=useRef<AbortController|null>(null);
 useEffect(()=>()=>request.current?.abort(),[]);
 async function inspect(){request.current?.abort();const controller=new AbortController();request.current=controller;setBusy(true);setValue(null);raw.current=null;setError('');try{const response=await fetch(`/api/paper/streams/${id}/intents`,{cache:'no-store',signal:controller.signal});if(!response.ok)throw Error(`订单意图核对未确认 (${response.status})`);const result=await response.json(),parsed=schema.parse(result);if(parsed.session_id!==id)throw Error('账户不一致');raw.current=result;setValue(parsed);}catch(e){if(!controller.signal.aborted)setError(String(e));}finally{if(!controller.signal.aborted)setBusy(false);}}
 return <section data-testid="paper-intents"><h2>独立模拟订单记录</h2><p>核对已经完成的模拟订单及其状态转换。不会提交或重放订单；执行前可恢复的待执行队列尚未实现。</p><button disabled={busy||disabled} onClick={()=>void inspect()}>核对独立模拟订单</button>{error?<p role="alert">{error}</p>:null}{value?<div data-testid="intent-result" data-coverage={value.coverage}><p>{value.coverage==='VERIFIED'?'独立记录已与账本完整核对':'旧账户尚未物化独立记录；不表示没有历史订单'} · 账本订单 {value.ledger_orders} · 独立记录 {value.durable_orders}</p><p>读取时点 UTC：{value.as_of}。状态路径在同一模拟事务中保存，不表示交易所提交或确认。</p><div className="research-table"><table><thead><tr><th>意图编号</th><th>来源</th><th>状态路径</th><th>保存时点 UTC</th></tr></thead><tbody>{value.intents.slice(-100).map(row=><tr key={row.intent_id}><td style={{overflowWrap:'anywhere'}}>{row.intent_id}</td><td>{row.origin==='BAR_ACCEPTANCE'?'闭合柱模拟':'历史回执物化'}</td><td>{row.transitions.join(' → ')}</td><td>{row.recorded_at}</td></tr>)}</tbody></table></div><button onClick={()=>{if(!raw.current)return;const url=URL.createObjectURL(new Blob([JSON.stringify(raw.current)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`fc666-paper-intents-${value.inputs_sha256}.json`;a.click();URL.revokeObjectURL(url);}}>下载独立模拟订单</button><p>下载保留完整冻结输入和原模拟回执，可离线复算；摘要不证明外部真实性。</p></div>:null}</section>;
}
