'use client';
import {useEffect,useRef,useState} from 'react';
import {z} from 'zod';
const summarySchema=z.object({authorization_id:z.string(),state:z.enum(['AWAITING_CONSUMPTION','FILLED','PARTIAL_CANCELLED','REJECTED','CANCELLED']),authorized_quantity:z.string().nullable(),cumulative_quantity:z.string(),cumulative_fees:z.string(),cumulative_notional:z.string(),unique_fills:z.number().int().nonnegative(),events:z.number().int().positive()});
const schema=z.object({version:z.literal('paper-local-lifecycle-v1'),session_id:z.uuid(),total_batches:z.number().int().nonnegative(),window_limit:z.literal(20),has_older:z.boolean(),trading_enabled:z.literal(false),automatic_replay:z.literal(false),external_reconciliation_supported:z.literal(false),batches:z.array(z.object({preparation_id:z.string(),status:z.string(),coverage:z.enum(['VERIFIED','LEGACY_UNAVAILABLE']),origin:z.string().nullable(),orders:z.array(z.object({summary:summarySchema,events:z.array(z.object({kind:z.enum(['CREATED','FILL','OUTCOME']),recorded_at:z.string()}))}))}))});
type Report=z.infer<typeof schema>;
const states:Record<string,string>={AWAITING_CONSUMPTION:'已创建，等待消费',FILLED:'模拟已成交',PARTIAL_CANCELLED:'模拟部分成交，余量结束',REJECTED:'模拟已拒绝',CANCELLED:'未消费，已取消'};
export default function Lifecycle({id,disabled}:{id:string;disabled:boolean}){
 const [value,setValue]=useState<Report|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');const request=useRef<AbortController|null>(null);
 useEffect(()=>()=>request.current?.abort(),[]);
 async function inspect(){request.current?.abort();const controller=new AbortController();request.current=controller;setBusy(true);setValue(null);setError('');try{const response=await fetch(`/api/paper/streams/${id}/lifecycle`,{cache:'no-store',signal:controller.signal});if(!response.ok)throw Error(`生命周期核对未确认 (${response.status})`);const parsed=schema.parse(await response.json());if(parsed.session_id!==id)throw Error('账户不一致');setValue(parsed);}catch(e){if(!controller.signal.aborted)setError(String(e));}finally{if(!controller.signal.aborted)setBusy(false);}}
 const rows=value?.batches.flatMap(batch=>batch.orders)??[];
 return <section data-testid="paper-lifecycle"><h2>独立模拟订单生命周期</h2><p>独立创建记录先保存；成交、最终结果或取消与消费事务一起保存。按事件序号核对累计数量、金额和费用，重复读取不增加成交。此处只读，不执行恢复。</p><button disabled={busy||disabled} onClick={()=>void inspect()}>核对模拟生命周期</button>{error?<p role="alert">{error}</p>:null}{value?<div data-testid="lifecycle-result"><p>共保存 {value.total_batches} 批次；本次仅核对最新20批次{value.has_older?'，更早记录不在本次范围':''}。旧批次无独立证据 {value.batches.filter(batch=>batch.coverage==='LEGACY_UNAVAILABLE').length}；不追认历史事件。</p>{rows.length?<div className="research-table"><table><thead><tr><th>授权关联编号</th><th>状态 / 事件路径</th><th>获准模拟量 / 累计量</th><th>累计金额 / 费用</th><th>唯一模拟成交数</th></tr></thead><tbody>{rows.slice(-100).map(row=><tr key={row.summary.authorization_id}><td style={{overflowWrap:'anywhere'}}>{row.summary.authorization_id}</td><td>{states[row.summary.state]}<br/>{row.events.map(event=>event.kind).join(' → ')}</td><td>{row.summary.authorized_quantity??'无获准成交'} / {row.summary.cumulative_quantity}</td><td>{row.summary.cumulative_notional} / {row.summary.cumulative_fees}</td><td>{row.summary.unique_fills}</td></tr>)}</tbody></table></div>:<p>此窗口尚无可核对的独立逐单事件。</p>}<p>最多展示100条订单。获准量是本次预计成交量，不表示策略全部需求量。本地模拟最多一次成交事件；私有交易所回报、ACK及真实成交与撤单竞态尚未接入。</p></div>:null}</section>;
}
