"use client";
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {z} from 'zod';
import {AccountList,ControlHistory} from '../accounts';
import {CandleSchema,Symbols,Intervals} from '../../../lib/market';
const D=z.string().regex(/^-?\d+(\.\d+)?([Ee][+-]?\d+)?$/),Time=z.iso.datetime({offset:true});
const Config=z.object({initial_cash:D,period:z.number().int(),fee_rate:D,slippage_rate:D,allocation:D,participation:D});
const Limits=z.object({max_order_quote:D,max_position_quote:D,max_drawdown:D});
const State=z.object({session_id:z.uuid(),revision:z.number().int().nonnegative(),status:z.enum(['RUNNING','PAUSED','STOPPED','BLOCKED','LIMIT_REACHED']),clock:Time,seed_bars:z.number().int().min(2),accepted_bars:z.number().int().nonnegative(),bar_limit:z.literal(1000),trading_enabled:z.literal(false),mode:z.literal('REALTIME_CLOSED_BAR_PAPER'),manifest:z.object({version:z.literal('spot-paper-closed-close-v1'),snapshot_sha256:z.string().regex(/^[0-9a-f]{64}$/),instrument:z.record(z.string(),z.unknown()),request:z.object({symbol:z.enum(Symbols),timeframe:z.enum(Intervals),limit:z.number().int(),strategy:z.enum(['ema_long_flat_v1','sma_long_flat_v1']),parameters:z.record(z.string(),z.unknown()),as_of:Time,config:Config,risk:Limits,max_lag_seconds:z.number().int()})}),seed:z.array(CandleSchema),observations:z.array(z.object({candle:CandleSchema,observed_at:Time,gate:z.enum(['ELIGIBLE','STALE_BAR','PAUSED','PRE_ACTIVATION'])})),account:z.object({cash:D,quantity:D,cost_basis:D,equity:D,realized_pnl:D,unrealized_pnl:D,net_pnl:D,fees:D,peak_equity:D,max_drawdown:D}),risk:z.object({entry_halted:z.boolean(),drawdown_halted:z.boolean(),manual_halt_at:z.number().int().nullable(),events:z.array(z.object({reason:z.string(),available_at:Time,drawdown:D}))}),feed:z.object({state:z.string(),expected_open:Time,checked_at:Time.nullable()}),orders:z.array(z.object({order_id:z.string(),side:z.enum(['BUY','SELL']),decision_at:Time,execution_at:Time,observed_at:Time,simulated:z.literal(true),status:z.enum(['FILLED','PARTIAL_CANCELLED','REJECTED']),reason:z.string().optional(),quantity:D.optional()})),fills:z.array(z.object({order_id:z.string(),side:z.enum(['BUY','SELL']),decision_at:Time,execution_at:Time,observed_at:Time,simulated:z.literal(true),quantity:D,price:D,fee:D,realized_pnl:D,reference_close:D,cash_after:D,quantity_after:D})),equity:z.array(z.object({as_of:Time,cash:D,quantity:D,equity:D})),signals:z.array(z.object({target:z.enum(['LONG','FLAT']),available_at:Time})),pending:z.object({target:z.enum(['LONG','FLAT']),available_at:Time,status:z.literal('AWAIT_NEXT_CLOSED_BAR')}).nullable()}).superRefine((s,c)=>{
 const clock=Date.parse(s.clock);
 if(s.seed.length!==s.seed_bars||s.observations.length!==s.accepted_bars||s.seed_bars+s.accepted_bars>1000||s.equity.length!==s.seed_bars+s.accepted_bars||s.observations.some(row=>Date.parse(row.candle.close_time)>clock||Date.parse(row.observed_at)<Date.parse(row.candle.close_time))||s.fills.some(fill=>Date.parse(fill.execution_at)>clock||Date.parse(fill.decision_at)>=Date.parse(fill.execution_at)||Date.parse(fill.observed_at)<Date.parse(fill.execution_at))||s.signals.some(row=>Date.parse(row.available_at)>clock))c.addIssue({code:'custom',message:'Invalid realtime paper prefix'});
});
type View=z.infer<typeof State>;
const KEY='fc666.paper.stream.v1';
const defaultFields={symbol:'BTCUSDT',timeframe:'1m',limit:'120',period:'20',strategy:'ema_long_flat_v1',fast:'10',slow:'20',initial_cash:'10000',fee_rate:'0.001',slippage_rate:'0.0005',allocation:'0.5',participation:'0.01',max_order_quote:'5000',max_position_quote:'10000',max_drawdown:'0.2',max_lag_seconds:'15'};
const labels:Record<string,string>={WAITING:'等待下一根闭合柱',CURRENT:'已接受最新闭合柱',STALE:'闭合行情延迟，等待补数',GAP:'发现历史缺口，等待补数',DATA_REVISED:'已接受历史被修正，账户已阻断',DATA_MISSING:'已接受历史缺失，账户已阻断',RULES_CHANGED:'交易规则变化，账户已阻断',RUNNING:'正在运行',PAUSED:'暂停成交，继续更新指标',STOPPED:'已停止，不能恢复',BLOCKED:'已阻断，需创建新账户',LIMIT_REACHED:'达到1000根上限，已停止',STALE_BAR:'行情迟到，不补造历史成交',PRE_ACTIVATION:'账户创建前闭合的柱，不成交',ELIGIBLE:'及时闭合柱',MANUAL_HALT:'已停止新买入',MAX_DRAWDOWN:'回撤停止',MAX_ORDER_QUOTE:'超出单笔金额',MAX_POSITION_QUOTE:'超出持仓金额',MARKET_RULES_OR_CAPACITY:'市场规则或容量不足',NONPOSITIVE_PRICE:'价格规则拒绝'};
const money=(v:string)=>Number(v).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});
export default function RealtimePaper(){
 const [fields,setFields]=useState(defaultFields),[view,setView]=useState<View|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[worker,setWorker]=useState(false);
 const current=useRef<View|null>(null),raw=useRef<Record<string,unknown>|null>(null),locked=useRef(false);
 const set=(key:keyof typeof defaultFields,value:string)=>setFields(f=>({...f,[key]:value}));
 function adopt(data:Record<string,unknown>){const next=State.parse(data);if(current.current?.session_id===next.session_id&&next.manifest.snapshot_sha256!==current.current.manifest.snapshot_sha256)throw new Error('固定账户快照变化');if(current.current?.session_id===next.session_id&&next.revision<current.current.revision)return current.current;raw.current=data;current.current=next;setView(next);localStorage.setItem(KEY,next.session_id);return next;}
 function restore(v:View){const r=v.manifest.request;setFields({...defaultFields,...r.config,...r.risk,symbol:r.symbol,timeframe:r.timeframe,limit:String(r.limit),period:String(r.config.period),strategy:r.strategy,fast:String(r.parameters.fast??10),slow:String(r.parameters.slow??20),max_lag_seconds:String(r.max_lag_seconds)});}
 async function read(id:string,signal?:AbortSignal){const response=await fetch(`/api/paper/streams/${id}`,{cache:'no-store',signal:signal??AbortSignal.timeout(15000)});if(!response.ok)throw new Error('实时模拟账户读取失败');return await response.json();}
 useEffect(()=>{const id=localStorage.getItem(KEY);if(!id||!z.uuid().safeParse(id).success)return;const abort=new AbortController();locked.current=true;setBusy(true);void read(id,abort.signal).then(data=>{if(!abort.signal.aborted)restore(adopt(data));}).catch(()=>{if(!abort.signal.aborted)setError('恢复账户失败，请检查服务状态');}).finally(()=>{if(!abort.signal.aborted){locked.current=false;setBusy(false);}});return()=>abort.abort();},[]);
 useEffect(()=>{let alive=true;let timer:ReturnType<typeof setTimeout>;const abort=new AbortController();async function poll(){try{const response=await fetch('/api/paper/status',{cache:'no-store',signal:abort.signal});const health=await response.json();if(alive)setWorker(health.status==='healthy');const id=current.current?.session_id;if(id&&!locked.current){const data=await read(id,abort.signal);if(alive&&current.current?.session_id===id)adopt(data);}}catch{if(alive){setWorker(false);setError('状态更新失败，保留最后确认账本');}}finally{if(alive)timer=setTimeout(poll,2000);}}void poll();return()=>{alive=false;abort.abort();clearTimeout(timer);};},[view?.session_id]);
 async function selectAccount(id:string){if(locked.current)return;locked.current=true;setBusy(true);setError('');try{const data=await read(id);if(data.session_id!==id)throw new Error('账户不一致');restore(adopt(data));}catch{setError('选择账户失败，保留最后确认账本');}finally{locked.current=false;setBusy(false);}}
 async function create(event:FormEvent){event.preventDefault();if(locked.current)return;locked.current=true;setBusy(true);setError('');current.current=null;raw.current=null;setView(null);localStorage.removeItem(KEY);
  try{const response=await fetch('/api/paper/streams',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({symbol:fields.symbol,timeframe:fields.timeframe,limit:Number(fields.limit),strategy:fields.strategy,parameters:fields.strategy==='ema_long_flat_v1'?{period:Number(fields.period)}:{fast:Number(fields.fast),slow:Number(fields.slow)},config:{initial_cash:fields.initial_cash,fee_rate:fields.fee_rate,slippage_rate:fields.slippage_rate,allocation:fields.allocation,participation:fields.participation,period:Number(fields.period)},risk:{max_order_quote:fields.max_order_quote,max_position_quote:fields.max_position_quote,max_drawdown:fields.max_drawdown},max_lag_seconds:Number(fields.max_lag_seconds)}),signal:AbortSignal.timeout(15000)});const data=await response.json();if(!response.ok)throw new Error(typeof data.detail==='string'?data.detail:'实时账户参数或历史不可用');adopt(data);}
  catch(e){setError(e instanceof Error?e.message:'创建失败');}finally{locked.current=false;setBusy(false);}
 }
 async function command(action:'pause'|'resume'|'halt'|'stop'){const before=current.current;if(!before||locked.current)return;locked.current=true;setBusy(true);setError('');let failure='操作未确认，已尝试读取服务器状态';try{const response=await fetch(`/api/paper/streams/${before.session_id}/command`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({expected_revision:before.revision,action,count:1}),signal:AbortSignal.timeout(15000)});if(!response.ok){if(response.status===409)failure='账户版本冲突，已尝试同步服务器状态';throw new Error(failure);}const data=await response.json();if(data.session_id!==before.session_id||data.manifest.snapshot_sha256!==before.manifest.snapshot_sha256)throw new Error('快照不一致');adopt(data);}catch{setError(failure);try{adopt(await read(before.session_id));}catch{/* Never retry a state mutation. */}}finally{locked.current=false;setBusy(false);}}
 const active=view&&['RUNNING','PAUSED'].includes(view.status);
 const input=(key:keyof typeof defaultFields,label:string,numeric=false,min?:number,max?:number)=><label key={key}>{label}<input required value={fields[key]} onChange={e=>set(key,e.target.value)} type={numeric?'number':'text'} inputMode={numeric?'numeric':'decimal'} min={min} max={max}/></label>;
 return <main className="research-page paper-page"><header><strong>FC666 · Paper</strong><a href="/">行情终端</a><a href="/portfolio">模拟组合</a><a href="/paper">历史模拟</a><a href="/replay">回放</a><span className="badge">实时闭合柱模拟 · 实盘关闭</span></header><h1>实时现货模拟账户</h1><p>后台消费已持久化的真实公共闭合柱。上一根目标在下一根及时到达的闭合柱收盘参考价模拟成交；迟到柱只更新指标，不补造过去成交。不是逐笔撮合或交易所下单。</p><p data-testid="paper-worker" data-healthy={worker} className={worker?'buy':'warning'}>{worker?'模拟 worker 在线':'模拟 worker 离线或状态未确认；请核对服务状态，页面保留最后确认账本'}</p>
 <AccountList kind="streams" selected={view?.session_id} revision={view?.revision} busy={busy} onSelect={selectAccount}/>
 <form className="research-form" onSubmit={create}><label>实时模拟策略<select aria-label="实时模拟策略" value={fields.strategy} onChange={e=>set('strategy',e.target.value)}><option value="ema_long_flat_v1">EMA Long / Flat v1</option><option value="sma_long_flat_v1">SMA Long / Flat v1</option></select></label><label>实时模拟交易对<select aria-label="实时模拟交易对" value={fields.symbol} onChange={e=>set('symbol',e.target.value)}>{Symbols.map(v=><option key={v}>{v}</option>)}</select></label><label>实时模拟周期<select aria-label="实时模拟周期" value={fields.timeframe} onChange={e=>set('timeframe',e.target.value)}>{Intervals.map(v=><option key={v}>{v}</option>)}</select></label>{input('limit','预热柱数',true,2,500)}{input('period','实时均线周期',true,2,500)}{fields.strategy==='sma_long_flat_v1'?<>{input('fast','实时 SMA 快周期',true,2,499)}{input('slow','实时 SMA 慢周期',true,Number(fields.fast)+1,500)}</>:null}{input('initial_cash','实时初始资金 USDT')}{input('max_order_quote','实时单笔买入上限 USDT')}{input('max_position_quote','实时持仓买入上限 USDT')}{input('max_drawdown','实时回撤停止阈值（0..1）')}{input('allocation','实时买入资金比例（0..1）')}{input('participation','实时前柱量参与率（0..0.1）')}{input('fee_rate','实时手续费率')}{input('slippage_rate','实时滑点率')}{input('max_lag_seconds','允许闭合柱延迟秒数',true,1,60)}<button disabled={busy} type="submit">创建实时模拟账户</button></form>{error?<p role="alert">{error}</p>:null}
 {view?<section data-testid="paper-stream-state" data-status={view.status} data-revision={view.revision} data-accepted={view.accepted_bars} data-fills={view.fills.length} data-halted={view.risk.entry_halted}><h2>{view.manifest.request.symbol} · {view.manifest.request.timeframe} · {labels[view.status]}</h2><p>预热 {view.seed_bars} 根，无历史成交；创建后已接受 {view.accepted_bars} 根 · 总上限1000根</p><p>最后闭合柱时钟 UTC：<time>{view.clock}</time></p><p data-testid="paper-stream-feed">{labels[view.feed.state]??view.feed.state} · 最后扫描 {view.feed.checked_at??'尚未扫描'}</p><div className="replay-controls"><button disabled={busy||!active} onClick={()=>void command(view.status==='PAUSED'?'resume':'pause')}>{view.status==='PAUSED'?'恢复实时模拟':'暂停实时成交'}</button><button disabled={busy||!active||view.risk.manual_halt_at!==null} onClick={()=>void command('halt')}>停止实时新买入</button><button disabled={busy||view.status==='STOPPED'} onClick={()=>void command('stop')}>停止此实时账户</button><button disabled={busy} onClick={()=>{if(!raw.current)return;const url=URL.createObjectURL(new Blob([JSON.stringify(raw.current,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`fc666-paper-stream-${view.session_id}-${view.accepted_bars}.json`;a.click();URL.revokeObjectURL(url);}}>下载实时模拟账本</button></div><p>暂停停止全部模拟成交，但继续接受闭合柱和更新指标；停止新买入仍允许策略卖出。停止账户不会自动平仓，保留资金和库存且不能恢复。被阻断或达到上限后需新建账户。</p>
 <div className="research-metrics">{[['现金 USDT',view.account.cash],['权益 USDT',view.account.equity],['库存数量',view.account.quantity],['已实现盈亏 USDT',view.account.realized_pnl],['未实现盈亏 USDT',view.account.unrealized_pnl],['费用 USDT',view.account.fees]].map(([label,value])=><div key={label}><small>{label}</small><strong title={value}>{label==='库存数量'?value:money(value)}</strong></div>)}</div><p>{view.risk.entry_halted?'新买入已被风控或手动停止':'买入须通过风控'} · 待处理目标 {view.pending?.target??'预热中'} · 最大观测回撤 {(Number(view.account.max_drawdown)*100).toFixed(2)}%</p>
 <details><summary>固定参数与执行限制</summary><p>{view.manifest.request.strategy} · {JSON.stringify(view.manifest.request.parameters)} · 初始资金 {view.manifest.request.config.initial_cash} · 延迟上限 {view.manifest.request.max_lag_seconds} 秒</p><p>费率 {view.manifest.request.config.fee_rate} · 滑点 {view.manifest.request.config.slippage_rate} · 资金比例 {view.manifest.request.config.allocation} · 前柱量参与率 {view.manifest.request.config.participation}</p><p>单笔买入上限 {view.manifest.request.risk.max_order_quote} · 买入后持仓上限 {view.manifest.request.risk.max_position_quote} · 回撤停止 {view.manifest.request.risk.max_drawdown}</p><p>成交价是收到闭合柱后的收盘价参考，不代表当时真实可成交报价；容量使用前柱量代理。金额显示两位小数，下载保留完整精度。断线后的迟到柱不会补造成交，已接受历史修正或规则变化会阻断账户。行情缺口不跳过，等待公共行情补数。当前无多用户鉴权。</p><p>修改表单只影响新账户。刷新恢复当前账户，网页关闭不停止后台运行。2秒轮询确认状态，命令冲突或丢失响应只读取、不自动重发。</p><p>初始快照 SHA256 {view.manifest.snapshot_sha256}</p></details>
 <h2>实时模拟成交 · 最近100笔</h2><div className="research-table"><table><thead><tr><th>参考收盘 UTC</th><th>观察时间 UTC</th><th>方向</th><th>数量</th><th>模拟价格</th><th>手续费</th></tr></thead><tbody>{view.fills.slice(-100).map(f=><tr key={f.order_id}><td>{f.execution_at}</td><td>{f.observed_at}</td><td>{f.side==='BUY'?'买入':'卖出'}</td><td>{f.quantity}</td><td>{f.price}</td><td>{money(f.fee)}</td></tr>)}</tbody></table></div><h2>实时模拟订单 · 最近100条</h2><div className="research-table"><table><thead><tr><th>参考收盘 UTC</th><th>方向</th><th>状态</th><th>数量 / 拒绝原因</th></tr></thead><tbody>{view.orders.slice(-100).map(o=><tr key={o.order_id}><td>{o.execution_at}</td><td>{o.side==='BUY'?'买入':'卖出'}</td><td>{o.status==='REJECTED'?'已拒绝':o.status==='PARTIAL_CANCELLED'?'部分成交，余量取消':'成交'}</td><td>{o.reason?(labels[o.reason]??o.reason):o.quantity}</td></tr>)}</tbody></table></div></section>:<p>创建后先用历史预热指标，资金和持仓从零交易状态开始，等待新的实时闭合柱。</p>}{view?<ControlHistory key={view.session_id} kind="streams" id={view.session_id} revision={view.revision}/>:null}</main>;
}
