'use client';
import {useEffect,useRef,useState} from 'react';
import {z} from 'zod';
const schema=z.object({version:z.literal('paper-stream-recovery-v1'),session_id:z.string().uuid(),revision:z.number().int(),account_status:z.string(),as_of:z.string(),ledger_clock:z.string(),recovery_state:z.enum(['NEEDS_REVIEW','BLOCKED_RETAINED','TERMINAL_RETAINED','WAITING_FOR_BAR','WORKER_UNCONFIRMED']),automatic_replay:z.literal(false),trading_enabled:z.literal(false),checks:z.object({ledger_reproduced:z.literal(true),unique_simulated_receipts:z.literal(true),instrument_rules_match:z.boolean(),accepted_source_match:z.boolean(),worker_healthy_at_read:z.boolean()}),feed:z.object({state:z.string()}),receipts:z.array(z.object({order:z.object({order_id:z.string(),side:z.string(),status:z.string(),execution_at:z.string()}),fill:z.object({quantity:z.string(),price:z.string(),fee:z.string()}).nullable()})),pending_decision:z.object({target:z.string(),status:z.literal('AWAIT_NEXT_CLOSED_BAR')}).nullable(),inputs_sha256:z.string()});
type Report=z.infer<typeof schema>;
const labels:Record<string,string>={NEEDS_REVIEW:'来源或规则不同，需要核对',BLOCKED_RETAINED:'保留已阻断账本',TERMINAL_RETAINED:'保留已停止或达到上限账本',WAITING_FOR_BAR:'持久账本可核对，等待下一闭合柱',WORKER_UNCONFIRMED:'模拟执行进程健康未确认'};
export default function Recovery({id,disabled}:{id:string;disabled:boolean}){
 const [value,setValue]=useState<Report|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');const raw=useRef<unknown>(null),request=useRef<AbortController|null>(null);
 useEffect(()=>()=>request.current?.abort(),[]);
 async function inspect(){request.current?.abort();const controller=new AbortController();request.current=controller;setBusy(true);setValue(null);raw.current=null;setError('');try{const response=await fetch(`/api/paper/streams/${id}/recovery`,{cache:'no-store',signal:controller.signal});if(!response.ok)throw Error(`恢复检查未确认 (${response.status})`);const result=await response.json();const parsed=schema.parse(result);if(parsed.session_id!==id)throw Error('账户不一致');raw.current=result;setValue(parsed);}catch(e){if(!controller.signal.aborted)setError(String(e));}finally{if(!controller.signal.aborted)setBusy(false);}}
 return <section data-testid="paper-recovery"><h2>只读执行恢复检查</h2><p>丢失响应后先核对持久账本和稳定模拟回执。检查不会重放成交、修复数据或恢复账户；待执行策略目标不是交易所订单。</p><button disabled={busy||disabled} onClick={()=>void inspect()}>检查持久执行状态</button>{error?<p role="alert">{error}</p>:null}
 {value?<div data-testid="recovery-result" data-state={value.recovery_state}><h3>{labels[value.recovery_state]}</h3><p>账户状态：{value.account_status}；版本 {value.revision}；行情接收状态 {value.feed.state}<br/>检查时点 UTC：{value.as_of}<br/>账本闭合柱时钟 UTC：{value.ledger_clock}</p><p>账本已复算；模拟回执唯一。历史来源 {value.checks.accepted_source_match?'一致':'不同'}，规则 {value.checks.instrument_rules_match?'一致':'不同'}，检查时 worker {value.checks.worker_healthy_at_read?'在线':'未确认'}。</p><p>PAUSED 账户即使账本一致也保持暂停；已停止或阻断账户不会被检查恢复。此结果只描述本次读取。</p><p>待处理目标：{value.pending_decision?.target??'无'}，仅等待后续闭合柱，不提交订单。</p><h3>稳定模拟回执 · 最近100条</h3><div className="research-table"><table><thead><tr><th>回执编号</th><th>方向 / 结果</th><th>执行参考 UTC</th><th>成交数量 / 价格 / 费用</th></tr></thead><tbody>{value.receipts.slice(-100).map(receipt=><tr key={receipt.order.order_id}><td style={{overflowWrap:'anywhere'}}>{receipt.order.order_id}</td><td>{receipt.order.side} / {receipt.order.status}</td><td>{receipt.order.execution_at}</td><td>{receipt.fill?`${receipt.fill.quantity} / ${receipt.fill.price} / ${receipt.fill.fee}`:'无成交'}</td></tr>)}</tbody></table></div><button onClick={()=>{if(!raw.current)return;const url=URL.createObjectURL(new Blob([JSON.stringify(raw.current)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download=`fc666-paper-recovery-${value.inputs_sha256}.json`;link.click();URL.revokeObjectURL(url);}}>下载执行恢复检查</button><p>完整账本与本次来源输入可离线复算；不是交易所成交确认或身份认证。</p></div>:null}</section>;
}
