"use client";
import {useEffect,useState,useRef} from 'react';
import {z} from 'zod';
const D=z.string().regex(/^-?\d+(\.\d+)?([Ee][+-]?\d+)?$/);
const T=z.iso.datetime({offset:true});
const List=z.object({items:z.array(z.object({session_id:z.uuid(),symbol:z.string(),timeframe:z.string(),status:z.string(),integrity:z.enum(['VERIFIED','INVALID'])})),next_cursor:z.string().nullable(),trading_enabled:z.literal(false)});
const Total=z.object({cash:D,initial_cash:D,market_value:D,equity:D,realized_pnl:D,unrealized_pnl:D,net_pnl:D,fees:D,gross_weight:D.nullable()});
const Report=z.object({version:z.literal('paper-portfolio-closed-minute-v1'),snapshot_sha256:z.string().regex(/^[a-f0-9]{64}$/),as_of:T,price_as_of:T,status:z.enum(['COMPLETE','UNAVAILABLE']),mode:z.literal('INDEPENDENT_PAPER_SCENARIO'),trading_enabled:z.literal(false),rows:z.array(z.object({session_id:z.uuid(),revision:z.number().int(),status:z.string(),reason:z.string().nullable(),ledger_clock:T.nullable(),symbol:z.string().nullable(),base:z.string().nullable(),cash:D.nullable(),quantity:D.nullable(),equity:D.nullable(),market_value:D.nullable(),quote:z.object({close:D,close_time:T,source:z.string()}).nullable()})),totals:Total.nullable(),exposures:z.array(z.object({base:z.string(),quantity:D,market_value:D,weight:D.nullable()})),alerts:z.array(z.object({code:z.string(),session_id:z.string().optional(),base:z.string().optional(),value:D.optional(),limit:D.optional()})),inputs:z.record(z.string(),z.unknown())}).superRefine((report,context)=>{if((report.status==='COMPLETE')!==(report.totals!==null)||report.rows.some(row=>row.ledger_clock!==null&&Date.parse(row.ledger_clock)>Date.parse(report.price_as_of))||Date.parse(report.price_as_of)>Date.parse(report.as_of))context.addIssue({code:'custom',message:'Invalid valuation clock or availability'});});
const labels:Record<string,string>={RUNNING:'运行中',PAUSED:'已暂停',STOPPED:'已停止',BLOCKED:'已阻断',LIMIT_REACHED:'已达上限',ACCOUNT_INTEGRITY:'账本核对失败',ACCOUNT_BLOCKED:'账户已阻断',RULES_CHANGED:'市场规则已变化',ACCEPTED_DATA_CHANGED:'已接受行情发生变化或缺失',ACCOUNT_LAGGING:'账户未处理应到达的闭合柱',QUOTE_MISSING:'缺少公共分钟报价',QUOTE_STALE:'公共分钟报价陈旧',UNSUPPORTED_INSTRUMENT:'币种或市场不支持',WORKER_UNAVAILABLE:'模拟 worker 心跳未确认',ENTRY_HALTED:'账户已停止新买入',GROSS_WEIGHT:'资产总敞口超过提示阈值',ASSET_WEIGHT:'单币种敞口超过提示阈值'};
const KEY='fc666.portfolio.selection.v1';
const money=(value:string)=>Number(value).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});
const percent=(value:string|null)=>value===null?'不可计算':`${(Number(value)*100).toFixed(2)}%`;
export default function Portfolio(){
 const [ids,setIds]=useState<string[]>([]),[cursor,setCursor]=useState<string|null>(null),[list,setList]=useState<z.infer<typeof List>|null>(null),[refresh,setRefresh]=useState(0),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[listError,setListError]=useState(''),[gross,setGross]=useState('0.8'),[asset,setAsset]=useState('0.6'),[view,setView]=useState<z.infer<typeof Report>|null>(null);
 const raw=useRef<Record<string,unknown>|null>(null),locked=useRef(false);
 useEffect(()=>{try{const saved=localStorage.getItem(KEY);if(saved){const parsed=z.array(z.uuid()).max(8).parse(JSON.parse(saved));setIds([...new Set(parsed)]);}}catch{setError('账户选择恢复失败，请重新选择');}},[]);
 useEffect(()=>{const abort=new AbortController();setLoading(true);setList(null);setListError('');const query=new URLSearchParams({limit:'10'});if(cursor)query.set('cursor',cursor);void fetch(`/api/paper/streams?${query}`,{cache:'no-store',signal:AbortSignal.any([abort.signal,AbortSignal.timeout(15000)])}).then(async response=>{if(!response.ok)throw new Error();return List.parse(await response.json());}).then(data=>{if(!abort.signal.aborted)setList(data);}).catch(()=>{if(!abort.signal.aborted)setListError('账户列表不可用，请刷新重试');}).finally(()=>{if(!abort.signal.aborted)setLoading(false);});return()=>abort.abort();},[cursor,refresh]);
 function choose(id:string){if(locked.current)return;const next=ids.includes(id)?ids.filter(value=>value!==id):[...ids,id];if(next.length>8)return;setIds(next);localStorage.setItem(KEY,JSON.stringify(next));setView(null);raw.current=null;}
 function clear(){if(locked.current)return;setIds([]);localStorage.removeItem(KEY);setView(null);raw.current=null;}
 async function value(){if(locked.current||!ids.length)return;locked.current=true;setBusy(true);setView(null);raw.current=null;setError('');try{const response=await fetch('/api/portfolio',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({session_ids:ids,limits:{max_gross_weight:gross,max_asset_weight:asset}}),signal:AbortSignal.timeout(20000)});const data=await response.json();if(!response.ok)throw new Error(response.status===404?'选择的实时账户不存在，历史账户不能纳入':'估值请求失败，请核对输入或服务状态');const report=Report.parse(data);if(JSON.stringify(report.rows.map(row=>row.session_id))!==JSON.stringify(ids))throw new Error('估值账户不一致');raw.current=data;setView(report);}catch(e){setError(e instanceof Error?e.message:'估值失败');}finally{locked.current=false;setBusy(false);}}
 return <main className="research-page"><header><strong>FC666 · Portfolio</strong><a href="/">行情终端</a><a href="/paper/realtime">实时模拟</a><a href="/paper">历史模拟</a><span className="badge">模拟场景 · 实盘关闭</span></header><h1>模拟账户组合估值</h1><p>显式选择1至8个独立实时模拟账户。资金各自独立，只作场景汇总，不代表真实共享资金或可交易组合。历史账户不纳入；报价使用同一已闭合分钟收盘参考价，不是可成交报价。</p>
 <section><h2>选择实时模拟账户</h2><button disabled={loading||busy} onClick={()=>setRefresh(value=>value+1)}>刷新候选账户</button>{loading?<p>正在读取…</p>:null}{listError?<p role="alert">{listError}</p>:null}<div className="research-table"><table><thead><tr><th>选择</th><th>账户</th><th>市场</th><th>状态</th></tr></thead><tbody>{list?.items.map(item=><tr key={item.session_id} data-account-id={item.session_id}><td><input type="checkbox" aria-label={`选择账户 ${item.session_id}`} checked={ids.includes(item.session_id)} disabled={busy||item.integrity==='INVALID'||(!ids.includes(item.session_id)&&ids.length===8)} onChange={()=>choose(item.session_id)}/></td><td style={{overflowWrap:'anywhere'}}>{item.session_id}</td><td>{item.symbol} · {item.timeframe}</td><td>{labels[item.status]??item.status}{item.integrity==='INVALID'?' · 账本异常':null}</td></tr>)}</tbody></table></div><button disabled={loading||busy||cursor===null} onClick={()=>setCursor(null)}>返回首批候选</button> <button disabled={loading||busy||!list?.next_cursor} onClick={()=>setCursor(list?.next_cursor??null)}>更早候选账户</button><p>已选择 {ids.length}/8，翻页保留选择；刷新仅恢复选择，不自动沿用旧估值。</p><ul>{ids.map(id=><li key={id} style={{overflowWrap:'anywhere'}}>{id} <button disabled={busy} onClick={()=>choose(id)}>移除此账户</button></li>)}</ul><button disabled={busy||!ids.length} onClick={clear}>清空选择</button></section>
 <section><h2>风险提示阈值</h2><label>总资产敞口 / 权益（0..1）<input aria-label="总资产敞口阈值" inputMode="decimal" disabled={busy} value={gross} onChange={event=>setGross(event.target.value)}/></label> <label>单币种敞口 / 权益（0..1）<input aria-label="单币种敞口阈值" inputMode="decimal" disabled={busy} value={asset} onChange={event=>setAsset(event.target.value)}/></label><p>阈值只产生风险提示，不阻止订单，不平仓，不修改账户风控。改变阈值后需重新估值。</p><button disabled={busy||!ids.length} onClick={()=>void value()}>计算当前模拟估值</button>{error?<p role="alert">{error}</p>:null}</section>
 {view?<section data-testid="portfolio-result" data-status={view.status}><h2>{view.status==='COMPLETE'?'本次估值完整':'本次估值不可汇总'}</h2><p>账户读取时点 UTC：{view.as_of}<br/>共同报价时点 UTC：{view.price_as_of}</p><p>这是一次只读快照；账户或行情随后变化不会更新此结果，请重新计算。已停止账户仍保留库存，需要报价才能估值。</p>{view.totals?<div className="research-metrics">{[['独立模拟初始资金合计',view.totals.initial_cash],['现金 USDT',view.totals.cash],['资产市值 USDT',view.totals.market_value],['权益 USDT',view.totals.equity],['已实现盈亏 USDT',view.totals.realized_pnl],['按共同报价未实现盈亏 USDT',view.totals.unrealized_pnl],['净盈亏 USDT',view.totals.net_pnl],['模拟费用 USDT',view.totals.fees]].map(([label,value])=><div key={label}><small>{label}</small><strong title={value}>{money(value)}</strong></div>)}</div>:<p role="alert">至少一个账户或报价未确认。总权益、总盈亏及敞口比例均不提供，不把缺失值当零。</p>}<div className="research-table"><table><thead><tr><th>账户 / 市场</th><th>账本时钟 UTC</th><th>现金 / 库存</th><th>报价 / 报价时钟</th><th>权益 / 状态</th></tr></thead><tbody>{view.rows.map(row=><tr key={row.session_id}><td style={{overflowWrap:'anywhere'}}>{row.session_id}<br/>{row.symbol??'市场未确认'}</td><td>{row.ledger_clock??'未确认'}</td><td>{row.cash??'未确认'} / {row.quantity??'未确认'}</td><td>{row.quote?.close??'无报价'}<br/>{row.quote?.close_time??''}</td><td>{row.reason?(labels[row.reason]??row.reason):row.equity}</td></tr>)}</tbody></table></div>{view.totals?<><p>总资产敞口 / 权益：{percent(view.totals.gross_weight)}</p><div className="research-table"><table><thead><tr><th>币种</th><th>合并数量</th><th>市值 USDT</th><th>市值 / 权益</th></tr></thead><tbody>{view.exposures.map(row=><tr key={row.base}><td>{row.base}</td><td>{row.quantity}</td><td>{money(row.market_value)}</td><td>{percent(row.weight)}</td></tr>)}</tbody></table></div></>:null}<h3>本次风险提示</h3>{view.alerts.length?<ul>{view.alerts.map((item,index)=><li key={index} style={{overflowWrap:'anywhere'}}>{labels[item.code]??item.code} {item.base??item.session_id??''}{item.value?` · ${percent(item.value)}，阈值 ${percent(item.limit??null)}`:''}</li>)}</ul>:<p>未触发本次已配置提示；不代表通过完整交易风险验收。</p>}<button onClick={()=>{if(!raw.current)return;const url=URL.createObjectURL(new Blob([JSON.stringify(raw.current,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download=`fc666-paper-portfolio-${view.snapshot_sha256}.json`;link.click();URL.revokeObjectURL(url);}}>下载本次估值快照</button><p>下载包含已知预热和接受的行情、账户账本及报价，可离线核对内部一致性，不证明数据来源或用户身份。金额显示两位小数，下载保留精度。无组合历史曲线或组合回撤，未启用实盘。</p></section>:null}</main>;
}
